# Site settings
title: Megan Girard | Inspire. Connect. Teach.
description: 'Inspire. Connect. Teach.'
url: 'https://www.megangirard.com/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Megan Girard'
  email: megan.lafave@hotmail.com
  twitter_username: MrsMGirard
  address: 'Long Sault, ON'

collections:
  projects:

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
